name = input('Enter your name: ')
address = input('Enter your address: ')
edu_bg = input('Enter your education background: ')
career = input('Enter your career: ')
like_stuff = input('Enter your like stuffs: ')
dislike_stuff = input('Enter your dislike stuffs: ')

print('Report--->')
print('You are ', name)
print('You live at ', address)
print('You carrer is ', career)
print('Stuffs you like are ', like_stuff)
print('Stuffs you dislike are ', dislike_stuff)
print('End report --------------------')
